# Mobile App for Lottery Addiction

Many people start playing the lottery for fun, but for some this activity turns into a habit which eventually escalates into addiction. Like other compulsive gamblers, lottery addicts soon begin spending from their savings and loans, they start to accumulate debts, and eventually engage in desperate behaviors like theft.

### Scenario
A medical institute that aims to prevent and treat gambling addictions wants to build a dedicated mobile app to help lottery addicts better estimate their chances of winning. The institute has a team of engineers that will build the app, but they need us to create the logical core of the app and calculate probabilities.

For the first version of the app, they want us to focus on the [6/49](https://en.wikipedia.org/wiki/Lotto_6/49) lottery and build functions that enable users to answer questions like:

- What is the probability of winning the big prize with a single ticket?
- What is the probability of winning the big prize if we play 40 different tickets (or any other number)?
- What is the probability of having at least five (or four, or three, or two) winning numbers on a single ticket?

The institute also wants us to consider historical data coming from the national 6/49 lottery game in Canada. The [data set](https://www.kaggle.com/datascienceai/lottery-dataset) has data for 3,665 drawings, dating from 1982 to 2018.


## Core Function

Throughout the project, we'll need to calculate repeatedly probabilities and combinations. As a consequence, we'll start by writing two functions that we'll use often:

- A function that calculates factorials; and
- A function that calculates combinations.


In [1]:
# Create a function for calculating factorial
def factorial(n):
    for i in range(n,1,-1):
        n *= i-1
    return n

# Create a function for calculating combinations where 
# k = number of selection
# n = number of objects to select from
def combinations(n,k):
    numerator = factorial(n)
    denominator = factorial(k)*factorial(n-k)
    return int(numerator/denominator)


## One-ticket Probability

In the 6/49 lottery, six numbers are drawn from a set of 49 numbers that range from 1 to 49. A player wins the big prize if the six numbers on their tickets match all the six numbers drawn. If a player has a ticket with the numbers {13, 22, 24, 27, 42, 44}, he only wins the big prize if the numbers drawn are {13, 22, 24, 27, 42, 44}. If only one number differs, he doesn't win.

For the first version of the app, we want players to be able to calculate the probability of winning the big prize with the various numbers they play on a single ticket (for each ticket a player chooses six numbers out of 49). So, we'll start by building a function that calculates the probability of winning the big prize for any given ticket.

We will write a function which takes in a list of six unique numbers and prints the probability of winning in a way that's easy to understand.

In [2]:
def one_ticket_probability(numbers):
    combination = combinations(49,6)
    probability = 1/combinations(49,6)
    # Round to percentage in 7 decimal places and convert to string type
    percentage = format(probability*100, '.7f')
    print ("The chance of winning the big prize in the 6/49 lottery with this combination is {}%. Simply put, the chance of winning is 1 in {}.".format(percentage, combination))
    
one_ticket_probability([1,2,3,4,5,6])
one_ticket_probability([12,24,35,45,15,6])

The chance of winning the big prize in the 6/49 lottery with this combination is 0.0000072%. Simply put, the chance of winning is 1 in 13983816.
The chance of winning the big prize in the 6/49 lottery with this combination is 0.0000072%. Simply put, the chance of winning is 1 in 13983816.


We wrote a function that can tell users what is the probability of winning the big prize with a single ticket. For the first version of the app, however, users should also be able to compare their ticket against the historical lottery data in Canada and determine whether they would have ever won by now.

## Historical Data Check for Canada Lottery

We'll now focus on exploring the historical data coming from the Canada 6/49 lottery. The data set can be downloaded from [Kaggle](https://www.kaggle.com/datascienceai/lottery-dataset).

In [3]:
import pandas as pd
canada_lottery = pd.read_csv('649.csv')
print(canada_lottery.shape)
canada_lottery.head(5)

(3665, 11)


PRODUCT  DRAW NUMBER  SEQUENCE NUMBER  DRAW DATE  NUMBER DRAWN 1  \
0      649            1                0  6/12/1982               3   
1      649            2                0  6/19/1982               8   
2      649            3                0  6/26/1982               1   
3      649            4                0   7/3/1982               3   
4      649            5                0  7/10/1982               5   

   NUMBER DRAWN 2  NUMBER DRAWN 3  NUMBER DRAWN 4  NUMBER DRAWN 5  \
0              11              12              14              41   
1              33              36              37              39   
2               6              23              24              27   
3               9              10              13              20   
4              14              21              31              34   

   NUMBER DRAWN 6  BONUS NUMBER  
0              43            13  
1              41             9  
2              39            34  
3              43            34  
4              47            45

In [4]:
canada_lottery.tail(5)

PRODUCT  DRAW NUMBER  SEQUENCE NUMBER  DRAW DATE  NUMBER DRAWN 1  \
3660      649         3587                0   6/6/2018              10   
3661      649         3588                0   6/9/2018              19   
3662      649         3589                0  6/13/2018               6   
3663      649         3590                0  6/16/2018               2   
3664      649         3591                0  6/20/2018              14   

      NUMBER DRAWN 2  NUMBER DRAWN 3  NUMBER DRAWN 4  NUMBER DRAWN 5  \
3660              15              23              38              40   
3661              25              31              36              46   
3662              22              24              31              32   
3663              15              21              31              38   
3664              24              31              35              37   

      NUMBER DRAWN 6  BONUS NUMBER  
3660              41            35  
3661              47            26  
3662              34            16  
3663              49             8  
3664              48            17

The data set contains historical data for 3,665 drawings (each row shows data for a single drawing), dating from 1982 to 2018. For each drawing, we can find the six numbers drawn in the 'NUMBER DRAWN' columns.

## Function for Historical Data Check

We're going to write a function that will enable users to compare their ticket against the historical lottery data in Canada and determine whether they would have ever won by now.

We need to be aware of the following details:

- Inside the app, the user inputs six different numbers from 1 to 49.
- Under the hood, the six numbers will come as a Python list and serve as an input to our function.
- The engineering team wants us to write a function that prints:
    - the number of times the combination selected occurred in the Canada data set; and
    - the probability of winning the big prize in the next drawing with that combination.


In [5]:
def extract_numbers(col):
    numbers = col[4:10]
    numbers = set(numbers)
    return numbers
canada_lottery.apply(extract_numbers, axis=1)

0        {3, 41, 11, 12, 43, 14}
1        {33, 36, 37, 39, 8, 41}
2         {1, 6, 39, 23, 24, 27}
3         {3, 9, 10, 43, 13, 20}
4        {34, 5, 14, 47, 21, 31}
5        {8, 41, 20, 21, 25, 31}
6       {33, 36, 42, 18, 25, 28}
7        {7, 40, 16, 17, 48, 31}
8        {5, 38, 37, 10, 23, 27}
9        {4, 37, 46, 15, 48, 30}
10        {33, 38, 7, 9, 42, 21}
11      {36, 11, 43, 17, 19, 20}
12       {37, 7, 14, 47, 17, 20}
13      {35, 44, 25, 28, 29, 30}
14       {36, 39, 8, 41, 47, 18}
15       {9, 12, 13, 14, 44, 48}
16       {4, 40, 43, 44, 14, 18}
17      {34, 35, 36, 13, 16, 18}
18      {36, 11, 23, 25, 28, 29}
19       {37, 7, 45, 18, 23, 25}
20      {37, 11, 45, 18, 19, 31}
21       {8, 14, 16, 48, 18, 31}
22       {4, 11, 45, 23, 24, 25}
23        {33, 34, 3, 4, 48, 19}
24       {5, 43, 17, 21, 28, 30}
25       {36, 6, 38, 46, 17, 24}
26        {4, 9, 10, 11, 43, 46}
27       {32, 33, 7, 13, 45, 23}
28      {35, 37, 11, 18, 22, 28}
29      {35, 45, 48, 25, 26, 31}
          

We will now create a function that takes in two inputs: a Python list containing the user numbers and a pandas Series containing sets with the winning numbers.

In [6]:
def check_historical_occurence(user_numbers):
    winning_numbers = canada_lottery.apply(extract_numbers, axis=1)
    user_numbers = set(user_numbers)
    matches = user_numbers == winning_numbers
    sum_of_matches = matches.sum()
    print ("The combination of numbers you have entered has occured {} times in the history of the Canadian lottery draws.".format(sum_of_matches))
    print ("The probability of winning the big prize in the next drawing with that combination is 1 out of {}".format(combinations(49,6)))

# Test our function with few inputs
check_historical_occurence([35, 37, 14, 48, 24, 31])
check_historical_occurence([1, 2, 3, 4, 5, 6])

The combination of numbers you have entered has occured 1 times in the history of the Canadian lottery draws.
The probability of winning the big prize in the next drawing with that combination is 1 out of 13983816
The combination of numbers you have entered has occured 0 times in the history of the Canadian lottery draws.
The probability of winning the big prize in the next drawing with that combination is 1 out of 13983816


## Multi-ticket Probability

Lottery addicts usually play more than one ticket on a single drawing, thinking that this might increase their chances of winning significantly. Our purpose is to help them better estimate their chances of winning — on this screen, we're going to write a function that will allow the users to calculate the chances of winning for any number of different tickets.

We need to consider the following details when creating our functions:

- The user will input the number of different tickets they want to play (without inputting the specific combinations they intend to play).
- Our function will see an integer between 1 and 13,983,816 (the maximum number of different tickets).
- The function should print information about the probability of winning the big prize depending on the number of different tickets played.


In [7]:
# Create a function that calculates the probability based on the number of tickets
def multi_ticket_probability(tickets):
    # Number of possible outcomes
    combination = combinations(49,6)
    probability = tickets/combination
    percentage = format(probability*100,'.7f')
    print ("The probability of winning the big prize with {} tickets is {}%.".format(tickets, percentage))

# Test the function with the following number of tickets in a list
tickets = [1, 10, 100, 10000, 1000000, 6991908, 13983816]
for t in tickets:
    multi_ticket_probability(t)

The probability of winning the big prize with 1 tickets is 0.0000072%.
The probability of winning the big prize with 10 tickets is 0.0000715%.
The probability of winning the big prize with 100 tickets is 0.0007151%.
The probability of winning the big prize with 10000 tickets is 0.0715112%.
The probability of winning the big prize with 1000000 tickets is 7.1511238%.
The probability of winning the big prize with 6991908 tickets is 50.0000000%.
The probability of winning the big prize with 13983816 tickets is 100.0000000%.


## Less Winning Numbers - Function

We're now going to write one more function to allow the users to calculate probabilities for two, three, four, or five winning numbers.

For extra context, in most 6/49 lotteries there are smaller prizes if a player's ticket match two, three, four, or five of the six numbers drawn. As a consequence, the users might be interested in knowing the probability of having two, three, four, or five winning numbers.

Below are the details we'll need to be aware of:

- Inside the app, the user inputs:
    - six different numbers from 1 to 49; and
    - an integer between 2 and 5 that represents the number of winning numbers expected
- Our function prints information about the probability of having the inputted number of winning numbers.


In [10]:
def probability_less_6(number):
    combination = combinations(6,number)
    successful_outcomes = combination*(49-(number+1))
    probability = successful_outcomes/combinations(49,6)
    percentage = format(probability*100, '.7f')
    print(print ("The probability of winning a prize with {} matching numbers is {}%.".format(number, percentage)))

# Test the function with all possible inputs
numbers = [2, 3, 4, 5]
for n in numbers:
    probability_less_6(n)

The probability of winning a prize with 2 matching numbers is 0.0049343%.
None
The probability of winning a prize with 3 matching numbers is 0.0064360%.
None
The probability of winning a prize with 4 matching numbers is 0.0047197%.
None
The probability of winning a prize with 5 matching numbers is 0.0018450%.
None


## Potential Improvement

We have created four main functions for our app:

- one_ticket_probability() — calculates the probability of winning the big prize with a single ticket
- check_historical_occurrence() — checks whether a certain combination has occurred in the Canada lottery data set
- multi_ticket_probability() — calculates the probability for any number of of tickets between 1 and 13,983,816
- probability_less_6() — calculates the probability of having two, three, four or five winning numbers

Possible features for a second version of the app include:

- Making the outputs even easier to understand by adding fun analogies (for example, we can find probabilities for strange events and compare with the chances of winning in lottery; for instance, we can output something along the lines "You are 100 times more likely to be the victim of a shark attack than winning the lottery").
- Combining the one_ticket_probability() and check_historical_occurrence() to output information on probability and historical occurrence at the same time.
- Creating a function similar to probability_less_6() which calculates the probability of having at least two, three, four or five winning numbers. Hint: the number of successful outcomes for having at least four winning numbers is the sum of these three numbers:
    - The number of successful outcomes for having four winning numbers exactly
    - The number of successful outcomes for having five winning numbers exactly
    - The number of successful outcomes for having six winning numbers exactly
